### ISSUE TITLE
Add template file (coordinates source) for Emlid Studio

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-Geotagger#24]
Attached are template that I did - should be verified, and sample of POS file generated from Emlid Studio

[25-EmLidStudioPOS.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182425/25-EmLidStudioPOS.zip)
[Reach-Rover_raw_20230624202211.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182431/Reach-Rover_raw_20230624202211.zip)

**Comment by mprokopyevwork** [comment]
Fixed in release 1.0.6
