### ISSUE TITLE
Geotagger updates SEG-Y file generated from Zond Aero LF GPR with wrong coordinates

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-Geotagger#25]
Attached are template of Emlid Studio generated POS file, SEG-Y file and corresponding position.csv file
After coordinates injection it is visible (in Prism2 for example) that coordinates in SEG-Y file are wrong (shape of trahjectory is absolutly different).

Original track:
<img width="377" alt="image" src="https://github.com/ugcs/UgCS-Geotagger/assets/21184180/60cb2114-d390-4870-8b69-8afd8239a4a9">

Track after coordinates injection:
<img width="380" alt="image" src="https://github.com/ugcs/UgCS-Geotagger/assets/21184180/7a4fd5e8-9586-4319-baf4-058fc349deca">

[Reach-Rover_raw_20230624202211.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182451/Reach-Rover_raw_20230624202211.zip)
[2023-06-24-20-23-00-gpr.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182462/2023-06-24-20-23-00-gpr.zip)
[2023-06-24-20-23-00-position.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182472/2023-06-24-20-23-00-position.zip)

**Comment by mprokopyevwork** [comment]
Fixed in release 1.0.6
