### ISSUE TITLE
Geotagger doesn't recognise files generated with latest Emlid Studio with GPST & UTC time for the POS file

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-Geotagger#26]
attached template and POS file

[Reach-Rover_raw_20230624202211.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182596/Reach-Rover_raw_20230624202211.zip)
[25-EmLidStudioPOS.zip](https://github.com/ugcs/UgCS-Geotagger/files/12182601/25-EmLidStudioPOS.zip)

**Comment by adobrovolskiy-ugcs** [comment]
It is necessary to create separate templates for POS files with GPST and UTC time, detect them by header

**Comment by adobrovolskiy-ugcs** [comment]
[ReachDS_raw_202308291042 UTC.zip](https://github.com/ugcs/UgCS-Geotagger/files/12584780/ReachDS_raw_202308291042.UTC.zip)

**Comment by mprokopyevwork** [comment]
Fixed in release 1.0.6
