### ISSUE TITLE
Geotagger doe not read time from SEG-Y files and can't proceed them

### ISSUE THREAD

**Issue by janisjonins** [ugcs/UgCS-Geotagger#27]
Time from SEG-Y file is not read, file can't be processed. Time for file is not read

![image](https://github.com/ugcs/UgCS-Geotagger/assets/47666352/78e4f1f8-6967-4847-b0da-7868fcdcc50f)

**Comment by mprokopyevwork** [comment]
Fixed in release 1.0.6
