### ISSUE TITLE
Version check for Emlid templates

### ISSUE THREAD

**Issue by janisjonins** [ugcs/UgCS-Geotagger#29]
It is necessary to update 50-RTKLibEmlidStudioGPTS.yaml and 60-RTKLibEmlidStudioUTC.yaml templates, replacing hardcoded version check with variable

**Comment by adobrovolskiy-ugcs** [comment]
lines 
match-regex: "(^% program   : ES 1\\.**7**).*?(^%  GPST).*?"

should be replaced with something like

match-regex: "(^% program   : ES 1\\.?).*?(^%  GPST).*?"

**Comment by mprokopyevwork** [comment]
Done. New Release 1.0.7 done.

**Comment by mprokopyevwork** [comment]
v1.0.7
